### ISSUE TITLE
Add jquery to repo

### ISSUE THREAD

**Issue by pconerly** [mattrock23/eclipse-combat-simulator#6]
![screen shot 2014-12-30 at 11 49 53 am](https://cloud.githubusercontent.com/assets/469808/5883758/6625cb7e-a30a-11e4-9ddb-d715d08f58d7.png)

jquery is missing, so it's broken.

I can't find your email otherwise I'd email the next part but--- are you interested in working with me to fix this up?  Apparently I was wrong about this being the same simulator as http://boardgamegeek.com/thread/824766/eclipse-battle-simulator, and there's another simulator http://codesavior.com/space/simulator.php but it's down.

Sorry for spamming your issues :) If you're not interested then I'll probably go build it on my own.

**Comment by mattrock23** [comment]
Yeah, I just built this as an exercise to learn javascript. I haven't played eclipse in over a year so I don't even remember the rules.

You are welcome to use any of my code if it helps you though.
